name: animate_text
description: "Helps you to animate text easy with scale, opacity, transform, blur."
version: 1.0.0
homepage: https://github.com/RathaIct/AnimateText
repository: https://github.com/RathaIct/AnimateText
issue_tracker: https://github.com/RathaIct/AnimateText/issues
maintainer: Hin Ratha (@RathaIct)
topics: [animate-text, animation-text, animated]
screenshots:
  - description: "AnimateText thumbnail "
    path: thumbnail.png
  - description: "AnimateText sample "
    path: thumbnail.gif
  - description: "AnimateText sample two"
    path: animated_text.gif

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
