name: animate_text
description: "Create text animation easy with scale, opacity, transform, blur."
version: 0.0.3
homepage: https://github.com/RathaIct/AnimateText
maintainer: Hin Ratha (@RathaIct)

environment:
  sdk: ">=3.3.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
